### ISSUE TITLE
Documenter utilisation des notebooks --> dans le README, doc qui explique à quoi sert quel notebook

### ISSUE THREAD

**Issue by ODAncona** [student-GML/crapauduc#29]
Fichier regroupant tous le travail effectué et donnant une description exhaustive de chaque notebook et où le trouver. Avoir une image claire de notre nouvelle organisation de travail.

A savoir:
Datalake: Atlas
Répertoire de travail: Google Colab
Emplacement des Subsets: Google Drive
Emplacement de la documentation et du code: Github

**Comment by heryck237** [comment]
#29 closed
